// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQkb7LiJHPc-EtIOWmp_UzdzYI_0f3rtM',
    appId: '1:845784597777:web:fef3e725d8b57dae7238b0',
    messagingSenderId: '845784597777',
    projectId: 'edgemobileappbucse',
    authDomain: 'edgemobileappbucse.firebaseapp.com',
    storageBucket: 'edgemobileappbucse.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFaoozSLXtki0nUnEBGhLmrJhQZESwJ8c',
    appId: '1:845784597777:android:2e09b695a966dbbf7238b0',
    messagingSenderId: '845784597777',
    projectId: 'edgemobileappbucse',
    storageBucket: 'edgemobileappbucse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu9g0F06Nt1Ne8cptWb5Y3Oc_i6Q0wUKc',
    appId: '1:845784597777:ios:d4b5319abcc007937238b0',
    messagingSenderId: '845784597777',
    projectId: 'edgemobileappbucse',
    storageBucket: 'edgemobileappbucse.appspot.com',
    iosBundleId: 'com.example.test6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu9g0F06Nt1Ne8cptWb5Y3Oc_i6Q0wUKc',
    appId: '1:845784597777:ios:d4b5319abcc007937238b0',
    messagingSenderId: '845784597777',
    projectId: 'edgemobileappbucse',
    storageBucket: 'edgemobileappbucse.appspot.com',
    iosBundleId: 'com.example.test6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQkb7LiJHPc-EtIOWmp_UzdzYI_0f3rtM',
    appId: '1:845784597777:web:2d022d4051d9ec247238b0',
    messagingSenderId: '845784597777',
    projectId: 'edgemobileappbucse',
    authDomain: 'edgemobileappbucse.firebaseapp.com',
    storageBucket: 'edgemobileappbucse.appspot.com',
  );
}
